### ISSUE TITLE
UI Shell - Add code samples to website

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-website-gatsby#108]
We need to determine how the best way to display the latest UI Shell code on the website, and which pieces we want to highlight.

http://staging.carbondesignsystem.com/experimental/ui-shell/code 

@joshblack @aledavila

**Comment by joshblack** [comment]
The sections could be:

- UI Shell by default, like you have in the first panel
- UI Shell with expanded sidebar 
- UI Shell with Platform nav visible
- UI Shell with GPS visible

What's the process like for adding them to the website @alisonjoseph?

**Comment by alisonjoseph** [comment]
👍 

you use the `<component>` custom markdown component, where name is the title that shows up above the section, component is the core component and variation is the variation (would match the generated html file) So the UI shell looks like this 

```
<component 
    name="UI Shell"
    component="ui-shell"
    variation="ui-shell" 
    experimental="true"
    >
</component>
```

and here are all the options available for the component
```
```
<component
    name="Text Input" //Required
    component="text-input" //Required
    variation="text-input" //Required
    codepen="YEZLyd" //Optional - Adds link to codepen
    haslightversion="true" //Optional -If true shows the light/white background switcher
    hasReactVersion="true" //Optional -If true links to react storybook
    hasAngularVersion="true" //Optional -If true links to angular storkbook
    hasLightBackground="true" //Optional -If true has light background
    experimental="true" //Optional -If true loads experimental version/styles
    >
</component>
```
