### ISSUE TITLE
Gray background for component images is missing

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website-gatsby#138]
The previous website would use transparent backgrounds for component images and the grey background was generated by code. This means every png used for components had a transparent background. [Example png](http://www.carbondesignsystem.com/images/modal-usage-1.png) and [The png on page with a grey background](http://www.carbondesignsystem.com/components/modal/usage)

Is this something we want to cary over to the new Gatsby site? What was the reason to do this on the previous site?

**Comment by alisonjoseph** [comment]
@designertyler looks like its used for more than just images. there is some text displayed inside the box also as a caption. 

http://www.carbondesignsystem.com/components/checkbox/usage

need to port this over and fix all the component usage image styles
