### ISSUE TITLE
Search complete suggestions incomplete—Guidelines > Color page

### ISSUE THREAD

**Issue by lovemecomputer** [carbon-design-system/carbon-website-gatsby#163]
## Detailed description
when using search and viewing autocomplete results, the *Guidelines > Color* does not display as one of the options. I haven't done a full run-through yet to see what other pages are affected like this.
![screen shot 2018-10-01 at 2 39 00 pm](https://user-images.githubusercontent.com/3846271/46311530-1f878780-c588-11e8-8906-caea25913832.png)

> Is this issue related to a specific component?

need to determine

> What did you expect to happen? What happened instead? What would you like to see changed?

I expected *Guidelines > Color to be the top result.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

gatsby website

**Comment by alisonjoseph** [comment]
The search is currently indexing the live site, not the gatsby site.. so going to close this for now, however, we may have to do some more research into it once it's indexing the actual site.
