### ISSUE TITLE
Need https for internal site

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-website-gatsby#165]
Service workers need https to work

[Gatsby Docs](https://www.gatsbyjs.org/packages/gatsby-plugin-offline/)

`gatsby-plugin-offline`

**Comment by joshblack** [comment]
We should have SSL when using IBM Cloud, I don't think we force the HTTP connection though. The proxy URL is using HTTPS currently.

**Comment by alisonjoseph** [comment]
How do we force https?

**Comment by joshblack** [comment]
I think it'll be adding this line to our `Staticfile`:

```
force_https: true
```
