### ISSUE TITLE
Update Shell visuals to latest markup graphics

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon-website-gatsby#23]
The current [Carbon production guidelines](https://github.com/IBM/design-system-website/wiki/Production-guidelines) are based on the previous design language. Update the new Shell visuals to the latest Duo redlines style.

**Comment by shinytoyrobots** [comment]
Please provide a description of the deliverable for this issue above, thank you.

**Comment by shinytoyrobots** [comment]
This is not necessary before Carbon X, given it won't be until then that contribution guidelines to the Carbon website will change to reflect the updated IBM Design Language.

**Comment by claycrenshaw** [comment]
To clarify, the deliverable for this issue is a complete set of web-ready supporting images for the UI Shell documentation.

**Comment by claycrenshaw** [comment]
This work is not only updating to the new style, but also making fixes to the WIP graphics needed to ship UI Shell docs.

**Comment by shinytoyrobots** [comment]
As this blocks https://github.com/carbon-design-system/carbon-website-gatsby/issues/22, which is in the Q3 milestone, changed this milestone to Q3, too.
