### ISSUE TITLE
Experimental Component Styles inside Gatsby site

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-website-gatsby#27]
@asudoh still seeing some styling inconsistencies. 

Thanks so much for all your help on this! 

Gatsby Site
<img width="233" alt="screen shot 2018-09-13 at 8 27 58 pm" src="https://user-images.githubusercontent.com/2753488/45524369-b7693100-b793-11e8-9fb6-b33969277397.png">

vs. the dev env.
<img width="246" alt="screen shot 2018-09-13 at 8 28 03 pm" src="https://user-images.githubusercontent.com/2753488/45524367-b46e4080-b793-11e8-9f24-23c555330e0f.png">

Also, when I do a production build the styles don't appear at all.  Latest prod build -> https://carbon-design-system.github.io/carbon-website-gatsby/

**Comment by asudoh** [comment]
Hi @alisonjoseph do you have a quick instruction on how to create the production build? Thanks!

**Comment by alisonjoseph** [comment]
Sorry when I said dev env I meant `carbon-components` repo with experimental turned on, I'm seeing the same styles on gatsby dev and prod now. You can see that some of the styles for checkbox are not coming over for some reason. 

So this is what checkbox should look like and what it looks like in carbon-components
<img width="246" alt="screen shot 2018-09-13 at 8 28 03 pm" src="https://user-images.githubusercontent.com/2753488/45524367-b46e4080-b793-11e8-9f24-23c555330e0f.png">

and this is what is displaying on the Gatsby Site (both in dev and prod builds)
<img width="233" alt="screen shot 2018-09-13 at 8 27 58 pm" src="https://user-images.githubusercontent.com/2753488/45524369-b7693100-b793-11e8-9fb6-b33969277397.png">

Here is an example comparison of the focus styles with the DOM inspector between carbon-components and gatsby site.
<img width="992" alt="screen shot 2018-09-14 at 7 59 55 am" src="https://user-images.githubusercontent.com/2753488/45551650-41e17d00-b7f4-11e8-9e91-e047d2d2d3dd.png">
<img width="690" alt="screen shot 2018-09-14 at 7 59 31 am" src="https://user-images.githubusercontent.com/2753488/45551651-41e17d00-b7f4-11e8-9e9b-d9b646b3b1c0.png">
