### ISSUE TITLE
Guidance Page: sizing liquid boxes

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon-website-gatsby#29]
A user needs to understand the recommended sizing of liquid boxes.

DESIGN
- [ ] Sizing Liquid Boxes using Column Grid
- [ ] written content explanation
- [ ] design of guidelines on page

DEVELOPMENT
- [ ] link to content (v1)
- [ ] inline documentation on page (v2)

**Comment by kuehndaniel** [comment]
closing this issue as it's a duplicate of: https://github.com/carbon-design-system/carbon-website-gatsby/issues/25
