### ISSUE TITLE
Guidance Page: layering

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon-website-gatsby#30]
A user needs to understand the recommended layering approach.

DESIGN
- [ ] Layer (Z Index)
- [ ] written content explanation
- [ ] design of guidelines on page

DEVELOPMENT
- [ ] link to content (v1)
- [ ] inline documentation on page (v2)

**Comment by kuehndaniel** [comment]
closing this issue as it's a duplicate found here: https://github.com/carbon-design-system/carbon-website-gatsby/issues/25
