### ISSUE TITLE
Guidance Page: page geometry

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon-website-gatsby#31]
A user needs to understand an abstracted shell showing high level regions (header, navigation, panels etc.).

DESIGN
- [ ] reference Page Geometry (Regions) design work
- [ ] written content explanation
- [ ] design of guidelines on page

DEVELOPMENT
- [ ] link to content (v1)
- [ ] inline documentation on page (v2)

**Comment by kuehndaniel** [comment]
closing this issue as it's a duplicate of: https://github.com/carbon-design-system/carbon-website-gatsby/issues/25
