### ISSUE TITLE
Guidance Page: spacing and CSS box model

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon-website-gatsby#32]
A user needs to understand basic layout on a page with spacing guidance and our default CSS box model.

I want to have a page addressing Layout:

DESIGN
- [ ] visual example of spacing and the CSS Box Model
- [ ] written content explanation
- [ ] design of guidelines on page

DEVELOPMENT
- [ ] link to content (v1)
- [ ] inline documentation on page (v2)

**Comment by kuehndaniel** [comment]
closing this issue as it's a duplicate found here: https://github.com/carbon-design-system/carbon-website-gatsby/issues/25
