### ISSUE TITLE
Un-escapted character in Twitter handle

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon-website-gatsby#48]
![screen shot 2018-09-17 at 11 55 22 am](https://user-images.githubusercontent.com/3901764/45637638-9bee7680-ba70-11e8-83ce-b9101b511d9f.png)

URL: https://next.carbondesignsystem.com/getting-started/faq

**Comment by alisonjoseph** [comment]
fixed 👍  thanks Josh!
