### ISSUE TITLE
CSS bug on color swatch hover

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon-website-gatsby#50]
![screen shot 2018-09-17 at 11 58 40 am](https://user-images.githubusercontent.com/3901764/45637835-10291a00-ba71-11e8-88bf-b4c920c04127.png)

Expected behavior:
![screen shot 2018-09-17 at 11 59 08 am](https://user-images.githubusercontent.com/3901764/45637867-233bea00-ba71-11e8-85d7-c144df0690a1.png)

URL: https://next.carbondesignsystem.com/guidelines/color/swatches

**Comment by alisonjoseph** [comment]
good catch, so strange since I copied the css directly over for this. will take a look

**Comment by lovemecomputer** [comment]
on this one~

**Comment by lovemecomputer** [comment]
addressed in https://github.com/carbon-design-system/carbon-website-gatsby/pull/164
