### ISSUE TITLE
Accordion in left nav does not collapse when second level nav item is selected

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website-gatsby#71]
**Steps to reproduce**

- On [staging site](https://next.carbondesignsystem.com/guidelines/content/general)
- Click on Guidelines
- Select Accessability
- Try to collapse Guidelines.
(this happens on all sections - not just guidelines and accessibility)

**Expected result:**
Guidelines collapses

**Actual results:**
Guidelines stays open

<img width="256" alt="screen shot 2018-09-20 at 8 53 41 am" src="https://user-images.githubusercontent.com/19270502/45826764-ad2ac380-bcba-11e8-8f67-12e27c78e664.png">

**Comment by alisonjoseph** [comment]
No I don't think so, take a look at http://www.carbondesignsystem.com to see how it should be working. We just need to be able to open/close the subnavs even if a page inside is selected

**Comment by alisonjoseph** [comment]
re-opening. the fix I had broke the build
